version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: crewai-stock-analysis:latest
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      # 如未在 .env 中覆盖，下列变量提供默认值
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL:-https://api.openai.com/v1}
      WEB_HOST: ${WEB_HOST:-0.0.0.0}
      WEB_PORT: ${WEB_PORT:-5000}
    restart: unless-stopped
    command: ["python", "src/web_app.py"]
